[build]
  publish = "/"
  
[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"